name: Jekyll Site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jekyll/builder
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Jekyll site
      run: |
        jekyll build
        ls _site/
